### ISSUE TITLE
modalbox

### ISSUE THREAD

**Issue by AntonMezger** [DMKEBUSINESSGMBH/typo3-mkforms#105]
Hello,

When I use the renderlet MODALBOX I get a default modalbox. That modalbox I would like to customize.

How can I do that with my Template and or css?

best regards

Anton

**Comment by hannesbochmann** [comment]
You can add your own CSS as you like through TypoScript (page.includeJS...). This has nothing to do with mkforms. Adding a template only for the modalbox is not possible. But you can use an own template for the complete form. In this template you can deal with the modalbox widget as you like. You can add a template like this:

`<formidable version="2.0.296">
    <meta>
....
    </meta>
    <control>
        <renderer:TEMPLATE>
            <template>
                <path>EXT:myext/Resources/Private/Templates/Extensions/Mkforms/Form.html</path>
                <subpart>###FORM###</subpart>
                <errortag>errors</errortag>
            </template>
        </renderer:TEMPLATE>`

**Comment by AntonMezger** [comment]
Hello,

i found also a solution over the weekend:

define renderlet:MODALBOX name=mymodal" and in the html form add 


	<div class="modal-section">
		<table class="modal-table">
		<tr>
		<td colspan="2" align = "center" bgcolor="#CCCCCC">
			    <span class="modal-title">{modal-title}</span>		</td>
		</tr>
			<tr>
				<td colspan="2"><div align="center">{modal-content}</div></td>
			</tr>
			<tr>
				<td width="50%">{modal-cancelBox} </td>
				<td width="50%"> {modal-closeBox}</td>
			</tr>
	</table>
	</div>
		

many thanks
