### ISSUE TITLE
Move the widget JavaScript and CSS resources into Resources/Public/

### ISSUE THREAD

**Issue by oliverklee** [DMKEBUSINESSGMBH/typo3-mkforms#110]
Currently, the CSS and JavaScript of the resources still gets linked to paths like `typo3conf/ext/mkforms/widgets/listbox/res/js/listbox.min.js`, causing the resource to not get loaded if `helhum/typo3-secure-web` is used.

**Comment by hannesbochmann** [comment]
This should be fixed in current in current 11.5 branch.
