### ISSUE TITLE
Impossible to render line breaks in validation messages

### ISSUE THREAD

**Issue by digedag** [DMKEBUSINESSGMBH/typo3-mkforms#111]
I need to render some formatted code in validation error messages. Unfortunally all html tags are escaped because [jQuery function text() is used to render these messages](https://github.com/DMKEBUSINESSGMBH/typo3-mkforms/blob/master/Resources/Public/JavaScript/jquery/wrapper.js#L388). 

@hbochmann and @rengaw83: Is there any reason for this? I would like to replace text() by html().

**Comment by hannesbochmann** [comment]
Maybe to prevent XSS? It's possible to use user data in validation messages. I'm pretty sure the user data will be escaped anyway. But in the end you need some custom code to insert user data into validation messages so everybody has to take care of escaping on their own. So it should be okay to user html() over text().

**Comment by rengaw83** [comment]
Changed in #112.
