### ISSUE TITLE
Add compatibility with TYPO3 10.4

### ISSUE THREAD

**Issue by oliverklee** [DMKEBUSINESSGMBH/typo3-mkforms#114]
For the seminars extension, I'll need a 10.4-compatible version of mkforms.

Do you have any plans in this regard? Do you need help with this?

**Comment by hannesbochmann** [comment]
There is a campaitble branch: https://github.com/DMKEBUSINESSGMBH/typo3-mkforms/tree/10.4

It will be made the default branch and will be tagged as soon as we use this version in a production environment without problems.

**Comment by oliverklee** [comment]
Great, thanks!

**Comment by oliverklee** [comment]
@hannesbochmann I'm currently working on a 10.4-compatible version of my [seminars extension](https://github.com/oliverklee/ext-seminars/wiki/Project-planning:-10LTS-compatibility). For this, a released, 10.4-compatible version of mkforms will be tremendously helpful. Would you be willing to release it?

(If I encounter any problems while testing, I will gladly report and bugs and provide PRs where I can.)

I'd also like to kindly ask you to review and merge my open PRs. They will make my work on 10.4-related bugs easier.

**Comment by hannesbochmann** [comment]
@oliverklee What's bothering you to use "^10@dev" as requirement for mkforms while you're developing? I still had no chance to really test mkforms in a TYPO3 10.4 environment and don't want to release something untested.

**Comment by oliverklee** [comment]
@hannesbochmann Thanks, I'll use `^10@dev` for testing and report/fix-via-PR any bugs I'll find. When everything works on my side, I'll appreciate a release so I can release the 10-compatible version as well. Thank you for your work on this extension!
