### ISSUE TITLE
Please drop the master and master-github branches

### ISSUE THREAD

**Issue by oliverklee** [DMKEBUSINESSGMBH/typo3-mkforms#127]
Hi, could you please drop the master and master-github branches? This can help avoid confusion regarding which branch is the right one for the main development work. Thanks!

**Comment by oliverklee** [comment]
@hannesbochmann gentle ping

**Comment by hannesbochmann** [comment]
@oliverklee In the moment the master branch is still used in legacy projects and therefore can't be deleted.
