### ISSUE TITLE
Please enable the PHP-CI workflow in GitHub actions

### ISSUE THREAD

**Issue by oliverklee** [DMKEBUSINESSGMBH/typo3-mkforms#130]
https://github.com/DMKEBUSINESSGMBH/typo3-mkforms/actions/workflows/phpci.yml

This allows pull requests to get checked by GitHub actions.

**Comment by oliverklee** [comment]
@hannesbochmann gentle ping

**Comment by hannesbochmann** [comment]
@oliverklee I enabled it.

**Comment by oliverklee** [comment]
@hannesbochmann Thanks! :heart:
