### ISSUE TITLE
typo3 9 oops with mkform 10.1.3

### ISSUE THREAD

**Issue by AntonMezger** [DMKEBUSINESSGMBH/typo3-mkforms#156]
Hello,

after updating from 9.5.2 to 10.1.3,  all xml files display "leider" ist ein Fehler aufgetreten.

(debugger tells:  rn.base | Fatal error for action tx_mkforms_action_FormBase)

with version 9.5.2 I had not this problem. why this comes up?

**Comment by hannesbochmann** [comment]
Does this happen in a composer based installation?

**Comment by AntonMezger** [comment]
no, updates of typo3 are done by logical links to a newer version and extensions by the extension manager

**Comment by AntonMezger** [comment]
I found the problem: the cache could not be created while in class.tx_mkforms_util_XMLParser the statement at line 147

GeneralUtility::mkdir_deep(\Sys25\RnBase\Utility\Environment::getPublicPath().'typo3temp/', $sCacheDir);

does not work. I replaced with 

tx_mkforms_util_Div::mkdirDeep(\Sys25\RnBase\Utility\Environment::getPublicPath().'typo3temp/', $sCacheDir);

and it works like a charm.

see modification in https://github.com/AntonMezger/sdgziel

**Comment by hannesbochmann** [comment]
Problem is fixed and released in version 10.1.4.
