### ISSUE TITLE
mkforms majix

### ISSUE THREAD

**Issue by AntonMezger** [DMKEBUSINESSGMBH/typo3-mkforms#157]
Hi,

majix was well working in version 9.5.2.  with version 10.1.3 only the spinner appears for a short moment, but the codebehind does not get called. Is there some difference between the 2 versions and something more or different has to be specified?

best regards

**Comment by AntonMezger** [comment]
Hi,

I found one problem:

the change in class.tx_mkforms_js_Loader.php on line 189 and 191 to ?mkformsAjaxId= does not work in our case. I reverted it back  to index.php?eID=.  and registered eID
It still does not work, I have to do some more work on it. At least I do not get an error 500 from the server but now 200. The data is empty.

For the time being I have no clue. Does the new version be spefically typo3 10 and this feature not working for typo3 9?


by the way the changes I made for version 10.1.3 can be found in http:s//github.com/AntonMezger/sdgziel

**Comment by hannesbochmann** [comment]
Version 10.x should be compatible to TYPO3 9.5 but we had no time to check that. Your problem seems to be that the middleware DMK\MkForms\Middleware\AjaxHandler isn't executed. Could you check that?

**Comment by AntonMezger** [comment]
I could not really debug the problem. ajx calls worked in version 9.5.2, but do not work anymore in version 10.1.3.

I could not find the problem. 

in version 10 I have as link in the ajaxcall in file wrapper.js
http://localhost/sdgzielv2/?mkformsAjaxId=tx_mkforms_ajax&object=tx_ameosformidable&servicekey=ajaxevent

and in version 9 I have as link:

http://localhost/sdgzielv2ok/index.php?eID=tx_mkforms_ajax&object=tx_ameosformidable&servicekey=ajaxevent

There is a difference in what is posted to the page. the post with the version 10.1.3 lacks the modalbox. I join the two screenshots for both cases.

can you do something with this information ?
![snap_10-1-3](https://user-images.githubusercontent.com/12997672/211280514-98923451-514d-45a1-bebf-7dca311aeab6.jpg)
![snap_9-5-2](https://user-images.githubusercontent.com/12997672/211280543-0713e150-45c6-4a78-a2ff-4fda1650a7ee.jpg)

**Comment by AntonMezger** [comment]
to be more precise: the majixshowbox is used to verify majix calls. however majix calls do not work in version 10. 

The majix calls work fine in version 9, but I have to go to version 10 when upgrading typo. 

did you test the majix calls when upgrading from mkforms 9 to 10?

I also see that the page gets redirected, which should not happen?!

**Comment by AntonMezger** [comment]
Hello Hannes,

When I would give you access to a small example, would you take a look at it? I think you will find the problem very rapidly! (as I said before, I am willing to pay for the solution.)

best regards

Anton

**Comment by hannesbochmann** [comment]
@AntonMezger The problems with ajax requests have been fixed in version v11.0.5.
