### ISSUE TITLE
language problem in lister

### ISSUE THREAD

**Issue by AntonMezger** [DMKEBUSINESSGMBH/typo3-mkforms#159]
In case of a lister driven with ajax : <renderlet:LISTER name="pages" ajaxLister="true">

the lister first page will be in the correct language, however when changing page the language falls back to the first language in the language file. is there a work around?

**Comment by AntonMezger** [comment]
the language that is used will be the default language of typo3. did you not test such things?

**Comment by hannesbochmann** [comment]
No, I'm afraid we haven't as we barely use mkforms anymore.

**Comment by AntonMezger** [comment]
Hello Hannes,

I could not find where the things go wrong, so that I made a patch that works for me. in lister before the html is output I replace the strings that have to be retranslated. not very nice, but for our site that gives the correct results:

// we have a problem with mkforms when lister is in ajax mode. language labels will always be produced with
        // the default language (here german). This is a very bad patch that works only for our case
        $sLang = \Sys25\RnBase\Utility\Environment::getCurrentLanguageKey();
        $fileContent1 = file_get_contents('fileadmin/xml/locallang_sdg.xml');
        $fileContent2 = file_get_contents('typo3conf/ext/mkforms/widgets/lister/res/locallang/locallang.xml');
        $xml1 = \TYPO3\CMS\Core\Utility\GeneralUtility::xml2array($fileContent1);
        $xml2 = \TYPO3\CMS\Core\Utility\GeneralUtility::xml2array($fileContent2);

        if($sLang != 'de' ) {
            $aHtmlBag = $this->translateDefaultText($xml1, "Gesellschaft", $sLang, '</a>', $aHtmlBag);
            $aHtmlBag = $this->translateDefaultText($xml1, "BeraterIn", $sLang, '</a>', $aHtmlBag);
            $aHtmlBag = $this->translateDefaultText($xml1, "PatientIn", $sLang, '</a>', $aHtmlBag);
            $aHtmlBag = $this->translateDefaultText($xml1, "Zielerreichung", $sLang, '</a>', $aHtmlBag);
            $aHtmlBag = $this->translateDefaultText($xml1, "Text", $sLang, '</a>', $aHtmlBag);
            $aHtmlBag = $this->translateDefaultText($xml1, "Jahr", $sLang, '</a>', $aHtmlBag);
            $aHtmlBag = $this->translateDefaultText($xml1, "Datum", $sLang, '</a>', $aHtmlBag);
            $aHtmlBag = $this->translateDefaultText($xml1, "löschen", $sLang, '', $aHtmlBag);
            $aHtmlBag = $this->translateDefaultText($xml2, "&laquo;&laquo;erste", $sLang, '', $aHtmlBag);
            $aHtmlBag = $this->translateDefaultText($xml2, "&laquo;vorherige", $sLang, '', $aHtmlBag);
            $aHtmlBag = $this->translateDefaultText($xml2, "n&auml;chste&raquo;", $sLang, '', $aHtmlBag);
            $aHtmlBag = $this->translateDefaultText($xml2, "letzte&raquo;&raquo;", $sLang, '', $aHtmlBag);
        }

**Comment by AntonMezger** [comment]
This problem has been solved with the newest version  11. Thanks Hannes
