### ISSUE TITLE
majix once more

### ISSUE THREAD

**Issue by AntonMezger** [DMKEBUSINESSGMBH/typo3-mkforms#160]
I version 11 the majix calls are working again. however they only work for the default language, in my case german. In the other languages I get a status 404.

**Comment by hannesbochmann** [comment]
We will have a look at it.

**Comment by AntonMezger** [comment]
If it can help you, you may look att the site sgedziel.ch. The access was sent to tim by email. The test you will find under "Datenbank/majixtests". With German everything is fine, but not with the other languages.

have a nice weekend, best regards

Anton

**Comment by AntonMezger** [comment]
Hi,

I solved the problem. The problem lies not in mkforms but in the redirect handling of typo3 11. You can discard the problem.

best regards

Anton
