### ISSUE TITLE
Revert commit 83a051b50e71d694dd2a03a4f8832bb0e1f92767

### ISSUE THREAD

**Issue by oliverklee** [DMKEBUSINESSGMBH/typo3-mkforms#17]
This commit 83a051b50e71d694dd2a03a4f8832bb0e1f92767 (titled "Merge remote-tracking branch 'github/master'") just undoes many of my contributions. It looks like it was committed by accident and should be reverted as soon as possible.

**Comment by hannesbochmann** [comment]
What exactly was undone/is missing?

**Comment by oliverklee** [comment]
Oh, my fault. It looks like this commit actually _contains_ all the previous commits. Strange.

**Comment by oliverklee** [comment]
Sorry for the confusion! :-)

Just out of curiosity: How did this commit get in? (As far as I can see, it was not necessary from a technical standpoint.)

**Comment by hannesbochmann** [comment]
I merged the github master branch into our git master branch. I think I should have done a rebase instead.

**Comment by oliverklee** [comment]
Yes, a rebase would have been the way to go. :-)
