### ISSUE TITLE
Translate the German code comments to English

### ISSUE THREAD

**Issue by oliverklee** [DMKEBUSINESSGMBH/typo3-mkforms#2]
This will allow people to contribute who do not speak German. (English is the common accepted language for code comments in open-source projects.)

**Comment by rengaw83** [comment]
thats right, but it's the source code.
First and foremost it is important that the development team describes complex logics and understood these later.
some cases it's better to describe in the mother language of the core dev team.
for the time being we will invest no resources into the translation of the source code.
