### ISSUE TITLE
Add support for TYPO3 7.6

### ISSUE THREAD

**Issue by digedag** [DMKEBUSINESSGMBH/typo3-mkforms#28]
The extension should be compatible with T3 7.6 LTS. 
### Class Replacements
* [x] replace t3lib_extMgm
* [x] replace t3lib_div
* [x] replace other t3lib_-Classes

### Refactorings
* [x] replace Mailing in tx_ameosformidable::__sendMail
* [x] replace Mailing in tx_ameosformidable::_parseTsInBE
* [x] tx_mkforms_ds_db_Main::initDb()
* [x] tx_mkforms_ds_db_Main::_getSql()
* [x] formidableajax::_initBeUser()
* [x] tx_mkforms_util_Div::virtualizeFE()
* [x] tx_mkforms_util_Runnable::callTyposcript()
* [x] tx_mkforms_validator_file_Main::validate()
* [x] ux_t3lib_TSparser

### Plugin Update

**Comment by oliverklee** [comment]
:+1:

**Comment by hannesbochmann** [comment]
Not everything is tested but most features should be compatible now.
