### ISSUE TITLE
FAL-Support beim Upload

### ISSUE THREAD

**Issue by digedag** [DMKEBUSINESSGMBH/typo3-mkforms#33]
Unterstützt das Upload-Widget eigentlich schon FAL? Im Code konnte ich keinen Hinweis finden.
Die Umsetzung sollte ja ganz ähnlich wie bei DAM sein. Nur das wir hier zusätzlich noch den Referenz-Datensatz mit anlegen müssen.

Gibt es da schon was?

**Comment by hannesbochmann** [comment]
Das Upload Widget ist alt und wurde nicht angepasst. Michael hat das aber alles ins DAM Upload Widget integriert. Da ist zwar der Name irreführend aber da ging es wahrscheinlich um möglichst wenig Aufwand bei Upgrades.

**Comment by digedag** [comment]
:+1:

**Comment by rengaw83** [comment]
Am besten renderlet:MEDIAUPLOAD nutzen, dann ist es weniger verwirrend ;)
