### ISSUE TITLE
Implement majixSetHtml() to replace content of boxes 

### ISSUE THREAD

**Issue by digedag** [DMKEBUSINESSGMBH/typo3-mkforms#35]
Right now it is not possible to change the HTML content of simple box by majix commands. 

```xml
	<renderlet:BOX name="infobox">
	</renderlet:BOX>
```
The content should be filled by this command:
```php
	return array(
			$form->getWidget('infobox')->majixSetHtml('Hello world'),
	);
```

**Comment by rengaw83** [comment]
Das gab es schon und nennt sich `repaintInner`. 

Zumindest auf JavaScript Seite sollte dies nochmal umgestellt werden. 
Die setHtml auf dem Server könnte ja beibehalten werden, aber auf die `repaintInner` im JS zeigen.

In der Minimierten Fassung funktioniert es aktuell ohnehin nicht.

**Comment by digedag** [comment]
Die Implementierung sieht besser aus. Nur der Name ist blöd. Ich hab echt lange nach einer Möglichkeit gesucht. Irgendwas mit _set_ oder _replace_...
Ich werde setHtml als Alias umstellen.

Das minifiedJS muss tatsächlich neu erstellt werden. Da ist mir der Prozess aber unbekannt... :wink:
