### ISSUE TITLE
widget IMAGE should support FAL-References

### ISSUE THREAD

**Issue by digedag** [DMKEBUSINESSGMBH/typo3-mkforms#37]
If path is an integer and attribute treatIdAsReference is set to true, the image should be rendered.

```xml
<renderlet:IMAGE name="logofield" treatIdAsReference="true">
    <path>44</path>
```
Of course in a real usecase path will be set by userobj.

**Comment by rengaw83** [comment]
Als alternative kann man auch immer einen FluidViewhelper verwenden, damit ist man etwas flexibler:
```xml
<renderlet:FLUIDVIEWHELPER name="logofield" viewhelper="image">
	<params src="rdt:value">
		<param name="treatIdAsReference" value="true" />
		<param name="maxWidth" value="220" />
	</params>
</renderlet:FLUIDVIEWHELPER>
```
In diesem Fall steht im Feld logofield die uid der Referenz.

**Comment by digedag** [comment]
Das Problem ist nur, daß man die Referenz-ID erstmal in logofield reinbekommen muss. Normalerweise liegt da ja nur die Anzahl der Referenzen. Die Referenz-ID kann ich bei IMAGE über das Attribut **path** per **userobj** holen. In der Variante mit dem Fluidhelper fehlt mir da der Einstieg. Außerdem scheint man beim FluidHelper kein Typoscript nutzen zu können.

**Comment by rengaw83** [comment]
Du kannst alle Parameter, die der ViewHelper entgegennehmen kann, direkt im XML setzen.
Beispiel ImageViewHelper: https://fluidtypo3.org/viewhelpers/fluid/master/ImageViewHelper.html
TS ist an der Stelle nicht möglich, aber auch nicht nötig.
Um die Referenz-ID musst man dich kümmer, das ist aber in jedem Fall nötig, für singleimage hast du die entsprechende Methode ja bereits bereitgestellt.
