### ISSUE TITLE
Configure Renés, Michael's and Hannes' IDE to strip trailing whitespace on save

### ISSUE THREAD

**Issue by oliverklee** [DMKEBUSINESSGMBH/typo3-mkforms#5]
In PhpStorm:
File > Settings > Editor > General > Other > Strip trailing spaces on save: All

**Comment by hannesbochmann** [comment]
We did that already. But there are many files which we never touched as the come from the initial ameos extensions.

**Comment by oliverklee** [comment]
Okay, good to know. Thanks!
