### ISSUE TITLE
Crash in TYPO3 7.6: Closures are being serialized for codeBehinds and cached forms

### ISSUE THREAD

**Issue by oliverklee** [DMKEBUSINESSGMBH/typo3-mkforms#54]
Currently, my seminars FE editor crashed on two points. This is on TYPO3 CMS 7.6 with PHP 5.6.

Uncaught TYPO3 Exception
Serialization of 'Closure' is not allowed 

Exception thrown in file
/home/klee/src/typo3/ext/mkforms/util/class.tx_mkforms_util_Runnable.php in line 390.

Serialization of 'Closure' is not allowed 

Exception thrown in file
/home/klee/src/typo3/ext/mkforms/session/class.tx_mkforms_session_MixedSessionManager.php in line 82.

Serialization of 'Closure' is not allowed 

Exception thrown in file
/home/klee/src/typo3/ext/mkforms/session/class.tx_mkforms_session_MixedSessionManager.php in line 82.

This happens on one of my installations, but not on another installation with TYPO3 CMS 6.2. As both installations use the same version of mkforms (the current master), this looks like an incompatibility with TYPO3 CMS 7.6.

**Comment by oliverklee** [comment]
The problem in the Runnable class is that the form instance is being serialized. However, mkforms cannot now what class this is and that is does not include any closures. So it must not serialize this instance.

**Comment by oliverklee** [comment]
In the MixedSessionManager, a tx_mkforms_forms_base instance is being serialized. I have not been able to find out where exactly the closure is there. I propose to just not serialize this object here.

**Comment by hannesbochmann** [comment]
There can be tww reasons. Either there is a class which should be serialized but is not loaded. As you tested this in TYPO3 7.6 I suppose this is not the problem because of the autoloading. So the other reason is that indeed a closure should be serialzed which is not possible. 
The serialization can not be removed. So the only option is to find out where the closure comes from and to remove that closure. You need to check your runnables and code behind.

**Comment by oliverklee** [comment]
The TYPO3 Core itself uses closures, e.g., for $GLOBALS['TYPO3_CONF_VARS']. (That's where we noticed it in the PHPUnit extension.) I don't know which closure is the problem in this crash, though.

AFAIK, the TYPO3 Core is musing closures more and more, i.e., the runnables must not be contain references to instances of those classes. I find this problematic.

**Comment by hannesbochmann** [comment]
I guess you're right but unfortunately I don't see an easy solution to this problem. Maybe the caching for ajax requests needs to be refactored.
As this is time consuming I'm afraid there won't be a fix from our site in the near future. Feel free to contribute a pull request.

**Comment by oliverklee** [comment]
I've just added a workaround for this to my `oelib` extension that will solve this problem for my `seminars` extension: https://github.com/oliverklee/ext-oelib/pull/43

**Comment by rengaw83** [comment]
Its not a bug in mkforms, mkforms serializes the code behind to cache the form. On ajax calls mkforms unserializes the code behind to use it. When you have some stuff in the code behind, which can not be unserialized or is too big, you hav to handle it by your self.
I have no idea how to fix it generic in mkforms. We can't remove all properties on serialization. It is a feature that will be used in a lot of forms.

**Comment by oliverklee** [comment]
Okay, then closing this issue.
