### ISSUE TITLE
Error about hibernation when opening an Ajax modal editor

### ISSUE THREAD

**Issue by oliverklee** [DMKEBUSINESSGMBH/typo3-mkforms#55]
This is with TYPO3 6.2 and the latest trunk of mkforms.

In the FE editor of my seminars extension, I currently get the following error when I use the button for creating a new place (which should open a modal editor for places).

![screenshot_20170203_132234](https://cloud.githubusercontent.com/assets/765746/22591299/1add643a-ea14-11e6-88e5-8cdba41a3921.png)

Is this a bug? Or is this something I need to configure? (If so, then this ticket is about improving the error message and documentation so it is clear what is missing.)

**Comment by hannesbochmann** [comment]
When AJAX is used, the caching needs to be configured. This can be easily done in the extension manager. I updated the error message to make that more clear.

**Comment by oliverklee** [comment]
Thanks!
