### ISSUE TITLE
Ensure proper Composer Versions and Branches

### ISSUE THREAD

**Issue by ohader** [DMKEBUSINESSGMBH/typo3-mkforms#59]
* create `2.0` Branch from `2.0.13` Tag using `git branch 2.0 2.0.13`
* remove `version` definition in `composer.json` from development branches
  * remove this line from `2.0` branch
  * remove this line from `master` branch
  * this allows to use `composer require dmk/mkforms 2.0.x` for instance
* add this repository to the extension profile on typo3.org, which populates this repository to be available via composer.typo3.org

**Comment by ohader** [comment]
Example: https://github.com/ohader/typo3-mkforms/commit/daf8b17be87201b22bbabf1fc157cc78bbabb420

**Comment by hannesbochmann** [comment]
What do you need the branch 2.0 for?
This repository is already added as far as I see. You can check that on the extension page on typo3.org

**Comment by hannesbochmann** [comment]
Closed because version definition was removed and `composer require dmk/mkforms 2.0.x` can be used
