### ISSUE TITLE
renderlet:CHECKSINGLE is missing a input name

### ISSUE THREAD

**Issue by hlaranex** [DMKEBUSINESSGMBH/typo3-mkforms#61]
The output of the renderlet:CHECKSINGLE has missing a name-attribute in the input type checkbox. 

Cause is that in widgets/checksingle/class.tx_mkforms_widgets_checksingle_Main.php line 42 it says:

`'<input type="checkbox" id="%2$s_checkbox" %3$s %4$s value="1" />',`

Correct output can be archieved with

`'<input type="checkbox" name="%1$s" id="%2$s_checkbox" %3$s %4$s value="1"   />',`

**Comment by hannesbochmann** [comment]
That's not correct. If you use JS the correct name will be in the hidden field for that checkbox. The checkbox itself is more like a placeholder which syncs the actual hidden field when changes are made. This is because unchecked fields are not submitted.  
What do you need the name attribute for?

**Comment by hlaranex** [comment]
Thanks for the explanation. Your are totally correct. My mistake was, i deleted the whole "typo3temp"-folder, due to some cache problem, therefore i deleted the folder typo3temp/mkforms/" with the javascript for mkforms.

After i deinstalled and installed mkforms, the folder was build again and my form works as planed.
