### ISSUE TITLE
Release new version to the TER

### ISSUE THREAD

**Issue by oliverklee** [DMKEBUSINESSGMBH/typo3-mkforms#63]
Hi,

could you please release the next (or current) version to the TER (in addition to Packagist)? Thanks!

**Comment by oliverklee** [comment]
@digedag Could you please a new version to the TER? The version in the TER currently breaks the seminars extension with PHP 7.

**Comment by digedag** [comment]
Hey @oliverklee,
unfortunately I have no access to TER account. But I agree with you, that a new release should be published. Hopefully @hannesbochmann will found some time this week!!

**Comment by oliverklee** [comment]
@hannesbochmann It would be great if you could include PR #66 into the release. The PR fixes a bug that currently is a blocker for using mkforms in my seminars and onetimeaccount extensions with PHP 7 (which is required for TYPO3 CMS 8.7).

**Comment by hannesbochmann** [comment]
I'm trying to take care of that by tomorrow.

**Comment by oliverklee** [comment]
Thanks!

**Comment by hannesbochmann** [comment]
Just pushed the new version to the TER. Have fun!

**Comment by oliverklee** [comment]
Thanks! ❤️
