### ISSUE TITLE
Stop using the deprecated ::extRelPath in ext_tables.php

### ISSUE THREAD

**Issue by oliverklee** [DMKEBUSINESSGMBH/typo3-mkforms#69]
`ExtensionManagementUtility::extRelPath` has been deprecated in TYPO3 8.7. Instead, either EXT:... notation should be used (available since TYPO3 7.6 IIRC, but I'm not completely sure) or `PathUtility::getAbsoluteWebPath` (available since TYPO3 6.2) like this:

https://github.com/oliverklee/ext-phpunit/pull/47/files

**Comment by hannesbochmann** [comment]
Fixed with https://github.com/digedag/rn_base/commit/83443eddd2aaafc86cc56996a5170a747257bd74

**Comment by oliverklee** [comment]
Thanks!

There's also one place in mkforms that uses extRelPath and that needs to be changed.
