### ISSUE TITLE
Release version 3.0.20 to the TER

### ISSUE THREAD

**Issue by oliverklee** [DMKEBUSINESSGMBH/typo3-mkforms#86]
Hi @hannesbochmann, could you please also release version 3.0.20 to the TER so it's possible to get the bug fixes even when the TYPO3 installation is not in Composer mode? Thanks! :heart:

**Comment by hannesbochmann** [comment]
Version 3.0.21 should be available soon.

**Comment by oliverklee** [comment]
Thanks! :cookie:
